builders:
  autoloader_builder:
    target: ":velvet_annotation"
    import: "package:velvet_generator/src/builders/autoloader_builder.dart"
    builder_factories: ["autoloaderBuilder"]
    build_extensions:
      ".dart": [".velvet.dart"]
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
