name: velvet_generator
description: The code generator for the Velvet framework. It helps to automate
  some tasks as autoload, service binding, and more.
version: 0.0.1-dev.18
homepage: https://github.com/stratumfoundry/velvet/tree/main/packages/velvet_generator

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  analyzer: ^7.0.0
  build: ^2.4.1
  build_config: ^1.1.1
  flutter:
    sdk: flutter
  glob: ^2.1.2
  merging_builder:
    git:
      url: https://github.com/danieletulone/merging_builder
      ref: main
  quote_buffer: ^0.2.6
  source_gen: ^2.0.0
  velvet_annotation: ^0.0.1-dev.9
  velvet_support: ^0.0.1-dev.10

dev_dependencies:
  # Mandatory dependencies for make custom_lint work in monorepo
  custom_lint: ^0.7.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  velvet_custom_lints: ^0.0.1-dev.6

topics:
  - code-generation
  - framework
