include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_use_package_imports
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - prefer_single_quotes
    - use_enums
    - use_is_even_rather_than_modulo
    - require_trailing_commas
    - sort_constructors_first
    - sort_child_properties_last
    - use_setters_to_change_properties

analyzer:
  plugins:
    - custom_lint
  exclude:
    - "**.freezed.dart"
    - "**.g.dart"
    - "**.tailor.dart"
    - "**.velvet.dart"
    - "**/velvet_framework.dart"
    - "**/velvet_cli.dart"

custom_lint:
  rules:

dart_code_metrics:
  extends:
    - recommended
  metrics:
    # Function/Method
    cyclomatic-complexity: 10
    lines-of-code: 50
    maintainability-index: 50

    # Class
    coupling-between-object-classes: 12
    depth-of-inheritance-tree: 5
    number-of-added-methods: 10
    response-for-class: 55

    # File
    number-of-external-imports: 5

    technical-debt:
      threshold: 1
      todo-cost: 60
      ignore-cost: 120
      ignore-for-file-cost: 240
      as-dynamic-cost: 400
      deprecated-annotations-cost: 120
      file-nullsafety-migration-cost: 40
      unit-type: "EUR"
