name: velvet_cli
description: The CLI tool for the Velvet projects. It will help to speed up the
  development process.
version: 0.0.1-dev.5
homepage: https://github.com/stratumfoundry/velvet/tree/main/packages/velvet_cli

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  build: ^2.4.1
  dcli: ^6.0.5
  freezed_annotation: ^2.4.4
  get_it: ^7.7.0
  json_annotation: ^4.9.0
  path: ^1.8.0
  velvet_support: ^0.0.1-dev.10
  yaml: ^3.1.0
  yaml_mapper: ^0.0.4

dev_dependencies:
  build_runner: ^2.4.14
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  lints: ^3.0.0
  test: ^1.24.0

executables:
  velvet_cli: velvet_cli

platforms:
  linux:
  macos:
  windows:
