name: velvet_basic_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  connectivity_velvet_plugin: ^0.0.1-dev.3
  error_handling_velvet_plugin: ^0.0.1-dev.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  form_velvet_plugin: ^0.0.1-dev.1
  go_router: ^14.6.3
  riverpod_velvet_plugin: ^0.0.1-dev.1
  velvet_annotation: ^0.0.1-dev.9
  velvet_cli: ^0.0.1-dev.5
  velvet_framework: ^0.0.1-dev.54

dev_dependencies:
  build_runner: ^2.4.14
  custom_lint: ^0.7.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.7.2
  velvet_custom_lints: ^0.0.1-dev.6
  velvet_generator: ^0.0.1-dev.18

flutter:
  uses-material-design: true
  assets:
    - assets/translation/
    - .env

executables:
  ? velvet_basic_app
