name: velvet_annotation
description: "A package exposing annotations for velvel_generator. It is part of
  the Velvet framework."
version: 0.0.1-dev.9
homepage: "https://github.com/stratumfoundry/velvet/tree/main/packages/velvet_annotation"

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.7.0

dev_dependencies:
  custom_lint: ^0.7.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  velvet_custom_lints: ^0.0.1-dev.6

topics:
  - annotations
  - code-generation
