name: velvet_framework
description: A framework for building Flutter applications based on Riverpod and GoRouter.
version: 0.0.1-dev.54
homepage: https://github.com/stratumfoundry/velvet/tree/main/packages/velvet_framework

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  event_bus: ^2.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_i18n: ^0.35.1
  flutter_localizations:
    sdk: flutter
  get_it: ^7.7.0
  go_router: ^14.0.2
  logging: ^1.2.0
  mockito: ^5.4.4
  shared_preferences: ^2.2.3
  velvet_annotation: ^0.0.1-dev.9
  velvet_support: ^0.0.1-dev.10

dev_dependencies:
  build_runner: ^2.4.14

  # Mandatory dependencies for make custom_lint work in monorepo
  custom_lint: ^0.7.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  velvet_custom_lints: ^0.0.1-dev.6
  velvet_generator: ^0.0.1-dev.18

topics:
  - flutter
  - framework
