name: velvet_hooks
description: Provide support hooks for the everyday work with Flutter and Dart.
version: 0.0.1-dev.1
homepage: "https://github.com/stratumfoundry/velvet/tree/main/packages/velvet_hooks"

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  velvet_framework: ^0.0.1-dev.54

dev_dependencies:
  custom_lint: ^0.7.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  velvet_custom_lints: ^0.0.1-dev.6

topics:
  - dart
  - support
  - utilities
  - velvet-porting
