name: velvet_custom_lints
description: Custom lints for the Velvet projects. It will help to maintain the
  code quality.
version: 0.0.1-dev.6
homepage: https://github.com/stratumfoundry/velvet/tree/main/packages/velvet_custom_lints

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  analyzer: ^7.0.0
  analyzer_plugin: ^0.12.0
  custom_lint_builder: ^0.7.1
  yaml: ^3.1.2

topics:
  - lints
