library velvet_framework;

/// **************************************************************************
/// Velvet Framework
/// **************************************************************************
///
/// This is the core library of the framework that contains all the necessary classes and utilities to build a Flutter application.
///
/// In order to generate the file, run the following command:
// ```
// npx vscode-generate-index-standalone packages/velvet_framework/lib/
// ```

// @index(['./src/**/(*.dart)','!./src/**/*.g.dart','!./src/**/_*.dart','!./src/**/*.velvet.dart','!./src/**/*.freezed.dart'], f => `export '${f.path}.dart';`)
export './src/core/config/velvet_config.dart';
export './src/core/container/contracts/velvet_container_contract.dart';
export './src/core/container/mixins/proxy_to_get_it_mixin.dart';
export './src/core/container/velvet_container.dart';
export './src/core/env/config/dynamic_env_config.dart';
export './src/core/env/contracts/env_config_contract.dart';
export './src/core/env/events/env_read_event.dart';
export './src/core/event/bus/velvet_event_bus.dart';
export './src/core/event/configs/default_velvet_event_config.dart';
export './src/core/event/contracts/velvet_event_bus_contract.dart';
export './src/core/event/contracts/velvet_event_config_contract.dart';
export './src/core/event/events/velvet_event.dart';
export './src/core/event/observers/velvet_observer_from_events.dart';
export './src/core/event/observers/velvet_observer.dart';
export './src/core/event/plugins/velvet_event_plugin.dart';
export './src/core/event/subjects/velvet_subject.dart';
export './src/core/event/utils/dispatch.dart';
export './src/core/event/utils/listen.dart';
export './src/core/logger/channels/logging_velvet_logger_channel.dart';
export './src/core/logger/config/default_velvet_logger_config.dart';
export './src/core/logger/contracts/velvet_logger_config_contract.dart';
export './src/core/logger/contracts/velvet_logger_contract.dart';
export './src/core/logger/enums/velvet_log_severity_enum.dart';
export './src/core/logger/velvet_logger_channel.dart';
export './src/core/logger/velvet_logger.dart';
export './src/core/plugin/contracts/velvet_plugin_manager_contract.dart';
export './src/core/plugin/velvet_plugin_manager.dart';
export './src/core/plugin/velvet_plugin.dart';
export './src/core/utils/create_velvet_app.dart';
export './src/core/utils/env.dart';
export './src/core/utils/event_bus.dart';
export './src/core/utils/kernel.dart';
export './src/core/utils/logger.dart';
export './src/core/utils/navigator_key.dart';
export './src/core/utils/resolution_key.dart';
export './src/core/velvet_container.dart';
export './src/kernel/contracts/kernel_contract.dart';
export './src/kernel/events/hide_loading_widget_event.dart';
export './src/kernel/exceptions/kernel_is_already_running_exception.dart';
export './src/kernel/kernel.dart';
export './src/kernel/loaders/velvet_plugin_loader.dart';
export './src/kernel/mixins/setup_container_composition_mixin.dart';
export './src/kernel/mixins/setup_env_mixin.dart';
export './src/kernel/mixins/setup_event_but_mixin.dart';
export './src/kernel/mixins/setup_logger_mixin.dart';
export './src/kernel/mixins/setup_plugin_manager_mixin.dart';
export './src/kernel/mixins/setup_widgets_mixin.dart';
export './src/kernel/widgets/kernel_app_widget.dart';
export './src/kernel/widgets/kernel_error_debug_widget.dart';
export './src/kernel/widgets/kernel_error_widget.dart';
export './src/kernel/widgets/kernel_loading_widget.dart';
export './src/kernel/widgets/kernel_widget.dart';
export './src/router/config/default_velvet_router_config.dart';
export './src/router/contracts/velvet_router_config_contract.dart';
export './src/router/contracts/velvet_router_contract.dart';
export './src/router/enums/router_page_transition_enum.dart';
export './src/router/events/velvet_route_did_pop_event.dart';
export './src/router/events/velvet_route_did_push_event.dart';
export './src/router/events/velvet_route_did_remove_event.dart';
export './src/router/events/velvet_route_did_replace_event.dart';
export './src/router/events/velvet_route_did_start_user_gesture_event.dart';
export './src/router/events/velvet_route_did_stop_user_gesture_event.dart';
export './src/router/middleware/anonymous_velvet_middleware.dart';
export './src/router/middleware/velvet_middleware_pipeline.dart';
export './src/router/middleware/velvet_middleware.dart';
export './src/router/mixins/velvet_route_page_builder_mixin.dart';
export './src/router/observers/hide_loading_widget_observer.dart';
export './src/router/observers/velvet_proxy_router_observer.dart';
export './src/router/velvet_route.dart';
export './src/router/velvet_router_plugin.dart';
export './src/store/adapters/shared_preferences_velvet_store.dart';
export './src/store/contracts/velvet_store_adapter_contract.dart';
export './src/store/contracts/velvet_store_contract.dart';
export './src/store/velvet_storable.dart';
export './src/store/velvet_store_plugin.dart';
export './src/store/velvet_store.dart';
export './src/theme/config/default_theme_config.dart';
export './src/theme/contracts/theme_config_contract.dart';
export './src/theme/theme_velvet_plugin.dart';
export './src/translation/adapters/flutter_i18n_translator_adapter.dart';
export './src/translation/config/default_velvet_translation_config.dart';
export './src/translation/contracts/velvet_translation_config_contract.dart';
export './src/translation/contracts/velvet_translator_adapter_contract.dart';
export './src/translation/contracts/velvet_translator_contract.dart';
export './src/translation/events/locale_loaded_from_os.dart';
export './src/translation/events/locale_loaded_from_store.dart';
export './src/translation/exceptions/locale_not_available_exception.dart';
export './src/translation/mixins/interacts_with_velvet_translation_components.dart';
export './src/translation/storables/locale_storable.dart';
export './src/translation/utils/translate.dart';
export './src/translation/velvet_translation_plugin.dart';
export './src/translation/velvet_translator.dart';
export './src/utils/kernel_context.dart';
export './src/utils/navigator_context.dart';
export './src/validation/rules/bool/must_be_false_rule.dart';
export './src/validation/rules/bool/must_be_true_rule.dart';
export './src/validation/rules/confirmation_rule.dart';
export './src/validation/rules/email_rule.dart';
export './src/validation/rules/fixed_length_rule.dart';
export './src/validation/rules/max_length_rule.dart';
export './src/validation/rules/min_length_rule.dart';
export './src/validation/rules/required_string_rule.dart';
export './src/validation/velvet_rule.dart';
export './src/validation/velvet_validator.dart';
// @endindex
