name: velvet_support
description: Provide support utils for the everyday work with Flutter and Dart.
version: 0.0.1-dev.10
homepage: "https://github.com/stratumfoundry/velvet/tree/main/packages/velvet_support"

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Mandatory dependencies for make custom_lint work in monorepo
  custom_lint: ^0.7.1
  flutter_lints: ^5.0.0
  velvet_custom_lints: ^0.0.1-dev.6

topics:
  - dart
  - support
  - utilities
  - velvet-porting
